### ISSUE TITLE
Separate graphics from physics

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#10]
Maybe I should be commenting on the branch or something? Dunno, this seemed easy.

I like separating the stuff.

The arrow being separated is probably a good idea, although I do intend to have them
in the Model once I've got that set up (I think anyway).

In general, what's the crack with the 'internal' stuff? IIRC that means accessible to the same
assembly, but not others (unless an attribute is used)?

GravitySimulator is a public class for example, but then GameObjectFactory is internal?

NormalizeVectorBetween could be called DirectionBetween, or NormalizedDirectionBetween ?
Might just be me... ;)

Dinner time. More to come!

**Comment by mattwatson** [comment]
On 3 October 2012 20:40, DaveEmmerson notifications@github.com wrote:

> Maybe I should be commenting on the branch or something? Dunno, this
> seemed easy.

I think this was better. I'm a bit lazy raising issues - we could be using
them a lot more.

> I like separating the stuff.
> 
> The arrow being separated is probably a good idea, although I do intend to
> have them
> in the Model once I've got that set up (I think anyway).

Well my next idea is to show an arrow per force, rather than just the
resultant. Might be quite useful for checking that the forces are working
as expected.

> In general, what's the crack with the 'internal' stuff? IIRC that means
> accessible to the same
> assembly, but not others (unless an attribute is used)?
> 
> GravitySimulator is a public class for example, but then GameObjectFactory
> is internal?

Yeah you're right - the internal is assembly level accessibility
(effectively project in Visual Studio). In our case we only have one
assembly there's absolutely no difference =) It can be useful, for example
if you have classes which you don't want to leak over to another part of
the system. E.g. we might have a project for client and another for server.
Quite a few of the classes are totally specific to each part of the system.
Then we'd probably have another assembly which is shared stuff. For now
it's not that important, but the general rule is to make things as limited
as possible, and lower the restriction as and when you need to.

**Comment by mattwatson** [comment]
I moved all the physics stuff so far (gravity and forces) into the GameObject class, and in the process simplified the Ship and main game
