### ISSUE TITLE
Rotational forces

### ISSUE THREAD

**Issue by mattwatson** [DaveEmmerson/SpaceWar2#12]
Not sure if we should implement simple rotational forces, or make all forces have an offset from centre as well as a direction. Also to consider is angular momentum

So rotating a ship could be from thrusters that are off side facing, and off the centre. (They could automatically fire to stabiize the ship. Impacts from collisions could also cause the object to rotate.

Of course this might be not that fun, so a bit of experimentation will be needed.

**Comment by mattwatson** [comment]
I've added separate thrusters to ships. Not fully implemented yet. 
1) Thrust is not properly transformed based on ships rotation (this is a bug)
2) Thrust does not take into account location of the thrusters. This will be needed to Apply torque/moment to the ship as well as for spawning particles

**Comment by mattwatson** [comment]
Step 1) Get arrows drawing correctly to represent the thrusters
Step 2) Make the GameObject have angular equivalents to position, velocity and acceleration
Step 3) Figure out the equations to put in ApplyForce that will apply torque/moment to the ship.
Step 4) Make the rotation fly-by-wire. i.e. when you press rotate button, it 
     a) sets a target angular momentum 
     b) in the update loop automatically fires thrusters in order to achieve that target angular momentum
     c) when no button is pressed, sets target rotation to 0, so thrusters fire to stabilise the ship

**Comment by DaveEmmerson** [comment]
I can get the arrow drawing working I think, but it would be too complex. I must be missing something! :)

Maybe I should try to get the Models set up tonight after work. That would help. It's going to annoy me if I can't work it out.

**Comment by mattwatson** [comment]
If I remember correctly from opengl days...

Typically you would set all your vertices up and then apply the matrix
transformations to move them, rotate them and scale them separately (can't
remember if you did that before or after)

Seems like here the arrows should be drawn relative to the ship, and we
shouldn't have to care about which way the ship is facing or the ship's
position on the screen.

I don't know enough about xna yet do actually do this though :S

**Comment by DaveEmmerson** [comment]
Yeah, that's how it works, but you need the ship's world matrix. The way it's facing does matter too, I think, because you don't know if the force being passed in to the arrow creation is pointing the way it is because the ship is rotated or because the thruster points that way. That matters for transforming the offset. The offset needs to be rotated by any amount the ship has.

Definitely all linked with the models issue.

As it stands, we probably need to plot the direction arrow and thrust arrows and then transform them and the ship by a rotation matrix. Then plot the force matrices just relative to the ships' world matrix but not incorporating the rotation.

The arrow needs to be constructed on the basis of where the thruster points by default in the ship up position, and then the rotation done by the effect using the world matrix. I think the arrow is passed the effective thrust direction as it stands, but the offset is passed relative to the default position. That's what's causing the oddness.

I hope that makes.

**Comment by mattwatson** [comment]
Makes perfect sense. Think rather than getting it working, it would be
better to wait until the model stuff is done properly. Or at least do the
transformations somewhere else instead of in the arrow constructor

**Comment by DaveEmmerson** [comment]
I will try to get an arrow model drawn tonight and make attempt 10 at the model stuff. I need to stop thinking too ahead and just use the IJW pattern to start with and refactor later :)

**Comment by mattwatson** [comment]
Guessing what that means...

Lol good idea

**Comment by mattwatson** [comment]
Done
